spring:
  application:
    name: razorpay

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/razorpay}
    username: ${DB_USERNAME:rajnishkushwaha}
    password: ${DB_PASSWORD:Ranjit24}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 9090


vault:
  master-key: WTtGqMrItO8DwVD48GUO5zfwU2yc7f891/MdhSWBs7c=

payment:
  simulator:
    poll-interval-ms: 5000
    chaos-mode: NORMAL
    methods:
      card:
        min-delay-seconds: 2
        max-delay-seconds: 6
        success-rate: 90

      UPI:
        min-delay-seconds: 1
        max-delay-seconds: 3
        success-rate: 95

      NET_BANKING:
        min-delay-seconds: 4
        max-delay-seconds: 10
        success-rate: 80

jwt:
  secret-key: dont-use-in-production-ekh32837389owhjeg3782rdshqjvg32975d37286763ry237652ryedgf6


app:
  rate-limit:
    method: fixed
    use-case:
      api-key:
        requests-per-minute: 2